version: '3.7'
services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase-server-1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    mem_limit: 3g # Set the container memory limit to 3 GB
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8091/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
