@startuml
entity "Fact_Transactions" as Fact_Transactions {
    * transaction_id : UUID
    * user_id : UUID
    * product_id : UUID
    * date_id : Date
    * amount : Decimal
}

entity "Dim_User" as Dim_User {
    * user_id : UUID
    * first_name : String
    * last_name : String
    * email : String
    * city : String
    * birthdate : Date
    * age : Integer
}

entity "Dim_Product" as Dim_Product {
    * product_id : UUID
    * product_name : String
    * category : String
    * price : Decimal
}

entity "Dim_Date" as Dim_Date {
    * date_id : Date
    * year : Integer
    * quarter : String
    * month : Integer
    * day : Integer
    * weekday : String
}

Fact_Transactions }|--o{ Dim_User : "user_id"
Fact_Transactions }|--o{ Dim_Product : "product_id"
Fact_Transactions }|--o{ Dim_Date : "date_id"

@enduml
